---
language: "python"
services:
  - "docker"
python:
  - 3.6
  - 3.7

before_script:
  - "pip install invoke"
  - "invoke build-test-container -p $TRAVIS_PYTHON_VERSION"
script:
  - "invoke black -p $TRAVIS_PYTHON_VERSION"
  - "invoke bandit -p $TRAVIS_PYTHON_VERSION"
